### PR TITLE
Fixed the timezone to the local timezone of the browser.

### PR DESCRIPTION
**Pull request by vaibhav-305**
changed the timezone to the browser timezone of client.
It now displays date and time of the browser of client.

### CODE REVIEW

**Comment by sambhavsaxena** [comment]
@vaibhav-305 thanks for the effort but the date and timestamp is not constant yet, everytime you refresh the page, the time changes, can you make it constant some how and push the code again?

**Comment by vaibhav-305** [comment]
ok , will do

**Comment by vaibhav-305** [comment]
I've made the required changes, you can check

**Review by sambhavsaxena — APPROVED** [review]

**Comment by sambhavsaxena** [comment]
thanks @vaibhav-305 for your contribution:)

**Pull request merged**
